# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20161106_1819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bodeg_Detalle',
            new_name='Bodega_Detalle',
        ),
    ]
