# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20161106_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodega_detalle',
            options={'verbose_name': 'opcion', 'verbose_name_plural': 'Detalle de bodegas'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'opcion', 'verbose_name_plural': 'Productos del Invetnario'},
        ),
        migrations.AlterField(
            model_name='import_imventario',
            name='producto_costo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='import_imventario',
            name='producto_existencia',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='import_imventario',
            name='producto_precio',
            field=models.FloatField(default=0),
        ),
    ]
