# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_factura_factura_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.CharField(default='JOSE W. GARCIA', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='serie',
            field=models.CharField(default='A', max_length=2),
        ),
    ]
