# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_vendedor'),
        ('inventario', '0009_factura_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_usuario_vendedor', to='app.Vendedor'),
            preserve_default=False,
        ),
    ]
