# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_recibo_provicional_no_recibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='forma_pago',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
