# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_forma_pago_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo_provicional',
            name='comentario',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recibo_provicional',
            name='fecha_cobro_ck',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
