# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-23 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_auto_20161118_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='base_inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
