# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('simbolo', models.CharField(max_length=4)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo_Cambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambio', models.FloatField()),
                ('fecha', models.DateField()),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Moneda')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
