# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 20:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=14)),
                ('nombre', models.CharField(max_length=165)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=400)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('numero_ruc', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodoc', models.CharField(max_length=15, null=True, verbose_name='numero de documento')),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
                ('fecha_vence', models.DateField(blank=True, null=True)),
                ('pagada', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Factura_Abono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_abono', models.FloatField()),
                ('fecha_abono', models.DateField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Factura')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_completa', models.DateField(auto_now=True)),
                ('descripcion_resultado', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gestion_Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('numero_ruc', models.CharField(max_length=14)),
                ('nombre', models.CharField(max_length=165)),
                ('identificacion', models.CharField(max_length=14)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.TextField(max_length=600)),
                ('nodoc', models.CharField(max_length=15, null=True, verbose_name='numero de documento')),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'opcion',
                'verbose_name_plural': 'importacion de datos',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Gestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('resultados', models.ManyToManyField(blank=True, to='app.Gestion_Resultado')),
            ],
        ),
        migrations.AddField(
            model_name='gestion',
            name='resultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Gestion_Resultado'),
        ),
        migrations.AddField(
            model_name='gestion',
            name='tipo_gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tipo_Gestion'),
        ),
        migrations.AddField(
            model_name='gestion',
            name='usuario_completa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_completa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gestion',
            name='usuario_creacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='comentarios',
            field=models.ManyToManyField(to='app.Comentario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='gestiones',
            field=models.ManyToManyField(to='app.Gestion'),
        ),
    ]
