# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=14)),
                ('nombre', models.CharField(max_length=165)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('numero_ruc', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('numero_ruc', models.CharField(max_length=14)),
                ('nombre', models.CharField(max_length=165)),
                ('identificacion', models.CharField(max_length=14)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.TextField(max_length=600)),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
