# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='import',
            options={'verbose_name': 'opcion', 'verbose_name_plural': 'importacion de datos'},
        ),
        migrations.AddField(
            model_name='factura',
            name='nodoc',
            field=models.CharField(max_length=15, null=True, verbose_name='numero de documento'),
        ),
        migrations.AddField(
            model_name='import',
            name='nodoc',
            field=models.CharField(max_length=15, null=True, verbose_name='numero de documento'),
        ),
    ]
