# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='descripcion',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
