# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161101_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura_Abono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_abono', models.FloatField()),
                ('fecha_abono', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_vence',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factura_abono',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Factura'),
        ),
    ]
