# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161214_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='import_imventario',
            options={'verbose_name': 'opcion', 'verbose_name_plural': 'importacion de productos'},
        ),
        migrations.AddField(
            model_name='import',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='import',
            name='abono',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='impuesto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='monto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='nodoc',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='numero de documento'),
        ),
        migrations.AlterField(
            model_name='import',
            name='numero_ruc',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='import',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
