# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gestion_programacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='fecha_completa',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
