# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161215_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='identificacion',
            field=models.CharField(max_length=65),
        ),
    ]
