# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161104_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='fecha_completa',
            field=models.DateTimeField(null=True),
        ),
    ]
