# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161101_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_completa', models.DateField(auto_now=True)),
                ('descripcion', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Gestion_Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Gestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('resultados', models.ManyToManyField(blank=True, to='app.Gestion_Resultado')),
            ],
        ),
        migrations.AddField(
            model_name='gestion',
            name='resultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Gestion_Resultado'),
        ),
        migrations.AddField(
            model_name='gestion',
            name='tipo_gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tipo_Gestion'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='gestiones',
            field=models.ManyToManyField(to='app.Gestion'),
        ),
    ]
