# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161101_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente_comentario',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='cliente_comentario',
            name='comentario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='comentarios',
            field=models.ManyToManyField(to='app.Comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Cliente_Comentario',
        ),
    ]
