# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161215_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='celular',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
