# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 04:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20161101_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='usuario_completa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_completa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gestion',
            name='usuario_creacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
