# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
