# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-31 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profile_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='numero_inicial',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero Inicial para los recibos'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='serie',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Serie de Recibos'),
        ),
    ]
