# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 05:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20161101_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura_abono',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='factura_abono',
            name='fecha_abono',
            field=models.DateField(auto_now_add=True),
        ),
    ]
