# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_vendedor_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Empresa'),
            preserve_default=False,
        ),
    ]
