# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161101_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestion',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='gestion',
            name='comentario',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='gestion',
            name='descripcion_resultado',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
