# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cliente_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='celular',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(default=123, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='descripcion',
            field=models.CharField(default=123, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='impuesto',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='import',
            name='abono',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='import',
            name='celular',
            field=models.CharField(default=124, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='import',
            name='contacto',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='import',
            name='descripcion',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='import',
            name='impuesto',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='import',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
