# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161231_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name_plural': 'vendedores'},
        ),
    ]
