# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-23 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20161118_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento_abono',
            old_name='factura',
            new_name='documento',
        ),
    ]
