# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 05:10
from __future__ import unicode_literals

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bodega_Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existencia', models.FloatField(default=0.0)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Bodega')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_fac', models.CharField(max_length=10)),
                ('serie', models.CharField(default='A', max_length=2)),
                ('stotal', models.FloatField()),
                ('impuesto', models.FloatField()),
                ('total', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('anulada', models.BooleanField(default=False)),
                ('fecha_anulacion', models.DateTimeField(null=True)),
                ('comentario', models.CharField(max_length=200, null=True)),
                ('fecha_vence', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_factura_cliente', to='app.Cliente')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Moneda')),
                ('usuario_anulacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura_usuario_anulacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura_usuario_creacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Factura_Abono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_abono', models.FloatField()),
                ('fecha_abono', models.DateField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Factura')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Factura_Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('valor', models.FloatField()),
                ('entregado', models.BooleanField(default=False)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Bodega')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Factura')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Forma_Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_pedido', models.CharField(max_length=10)),
                ('stotal', models.FloatField()),
                ('impuesto', models.FloatField()),
                ('total', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('anulado', models.BooleanField(default=False)),
                ('fecha_anulacion', models.DateTimeField(null=True)),
                ('comentario', models.CharField(max_length=200, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cliente')),
                ('usuario_anulacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_usuario_anulacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_usuario_creacion', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_usuario_vendedor', to='app.Vendedor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido_Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('valor', models.FloatField()),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Bodega')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Pedido')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('serie', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('costo_promedio', models.FloatField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=app.models.get_media_url)),
            ],
            options={
                'verbose_name': 'opcion',
                'verbose_name_plural': 'Productos del Invetnario',
            },
        ),
        migrations.CreateModel(
            name='Producto_Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto_Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto_Medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recibo_Provicional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_recibo', models.IntegerField()),
                ('monto', models.FloatField()),
                ('cancelacion', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.CharField(max_length=600, null=True)),
                ('fecha_cobro_ck', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cliente')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Forma_Pago')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recibo_Provicional_User_Creacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto_Categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Empresa'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto_Marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto_Medida'),
        ),
        migrations.AddField(
            model_name='pedido_detalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto'),
        ),
        migrations.AddField(
            model_name='factura_detalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto'),
        ),
        migrations.AddField(
            model_name='bodega_detalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto'),
        ),
    ]
