# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='serie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
