# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20161106_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodeg_detalle',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='import_imventario',
            name='bodega',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='import_imventario',
            name='producto_costo',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='import_imventario',
            name='producto_precio',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='import_imventario',
            name='producto_serie',
            field=models.CharField(default=12341, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='serie',
            field=models.CharField(default=2345, max_length=50),
            preserve_default=False,
        ),
    ]
