# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-03 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20161201_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo_provicional',
            name='referencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
