# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_recibo_provicional_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
    ]
