# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-26 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20161221_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'Productos del Invetnario'},
        ),
        migrations.AddField(
            model_name='pedido',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recibo_provicional',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
    ]
