# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20161226_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forma_pago',
            options={'verbose_name': 'Forma de pago', 'verbose_name_plural': 'formas de pago'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'Productos del Inventario'},
        ),
        migrations.AlterModelOptions(
            name='recibo_provicional',
            options={'verbose_name': 'Recibo Provicional', 'verbose_name_plural': 'Recibos Provicionales de Caja'},
        ),
        migrations.AddField(
            model_name='pedido',
            name='no_pedido_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='stotal',
            field=models.FloatField(verbose_name='subtotal'),
        ),
    ]
