# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auto_20170105_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='no_pedido',
        ),
    ]
