# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161104_2317'),
        ('inventario', '0008_auto_20161109_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventario_factura_cliente', to='app.Cliente'),
            preserve_default=False,
        ),
    ]
