# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_remove_pedido_no_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='no_pedido_a',
            new_name='no_pedido',
        ),
    ]
