# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-06 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_auto_20170105_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo_provicional',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
    ]
