# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 14:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inventario.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20161118_1407'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0011_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura_Abono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_abono', models.FloatField()),
                ('fecha_abono', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forma_Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recibo_Provicional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('cancelacion', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cliente')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Forma_Pago')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recibo_Provicional_User_Creacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_vence',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=inventario.models.get_media_url),
        ),
        migrations.AddField(
            model_name='factura_abono',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Factura'),
        ),
        migrations.AddField(
            model_name='factura_abono',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
