# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_auto_20161118_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo_provicional',
            name='no_recibo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
